apiVersion: v1
kind: Service
metadata:
  name: {{ include "dyniva-chart.fullname" . }}
  labels:
    {{- include "dyniva-chart.labels" . | nindent 4 }}
spec:
  type:  {{ include "service.type" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePortEnabled }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "dyniva-chart.selectorLabels" . | nindent 4 }}